In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('../data/NY/vaccination.parquet.gzip')
df.head()

,Region,County,Partially Vaccinated,Fully Vaccinated,Report as of,POP2020,Non Vaccinated,Partially Vaccinated per Population,Fully Vaccinated per Population,Non Vaccinated per Population
0,Capital Region,Albany,74,0,2020-12-14,314848,314774,2.350340e-04,0.0,0.999765
1,Western New York,Allegany,0,0,2020-12-14,46449,46449,0.000000e+00,0.0,1.000000
2,New York City,"New York, Bronx, Kings, Richmond, Queens",2,0,2020-12-14,8804190,8804188,2.271646e-07,0.0,1.000000
3,Southern Tier,Broome,0,0,2020-12-14,198683,198683,0.000000e+00,0.0,1.000000
4,Western New York,Cattaraugus,0,0,2020-12-14,75467,75467,0.000000e+00,0.0,1.000000

In [7]:
df = df.sort_values(by=['Report as of'])
df.head()

,Region,County,Partially Vaccinated,Fully Vaccinated,Report as of,POP2020,Non Vaccinated,Partially Vaccinated per Population,Fully Vaccinated per Population,Non Vaccinated per Population
0,Capital Region,Albany,74,0,2020-12-14,314848,314774,2.350340e-04,0.0,0.999765
30,New York City,"New York, Bronx, Kings, Richmond, Queens",24,0,2020-12-14,8804190,8804166,2.725975e-06,0.0,0.999997
2,New York City,"New York, Bronx, Kings, Richmond, Queens",2,0,2020-12-14,8804190,8804188,2.271646e-07,0.0,1.000000
3,Southern Tier,Broome,0,0,2020-12-14,198683,198683,0.000000e+00,0.0,1.000000
4,Western New York,Cattaraugus,0,0,2020-12-14,75467,75467,0.000000e+00,0.0,1.000000

In [37]:
# check missing dates
def check_missing_dates(df, dateCol):
    subset = df.copy()
    subset = subset.set_index(dateCol)
    subset.index = pd.to_datetime(subset.index)
    print(pd.date_range(
        start="2020-12-14", end="2022-03-01").difference(subset.index))

In [39]:
df_final = pd.read_parquet('../data/final_dataset.parquet.gzip')
df_final.head()

,county,date,daily_cases,daily_cases_by_population,daily_deaths,daily_deaths_by_population,POP2020,Partially Vaccinated,Fully Vaccinated,Non Vaccinated,...,Number of ICU Beds By County,Number of ICU Beds Available By County,Total Beds By County per thousand ppl,Number of ICU Beds By County per thousand ppl,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,Albany,2021-01-01,11917,0.037850,205,0.000651,314848,5757.0,17.0,309091.0,...,153.0,22.0,3.849477,0.485949,-56.0,-38.0,-15.0,-71.0,-77.0,29.0
1,Albany,2021-01-01,11917,0.037850,205,0.000651,314848,5757.0,17.0,309091.0,...,153.0,22.0,3.849477,0.485949,-56.0,-38.0,-15.0,-71.0,-77.0,29.0
2,Albany,2022-01-01,41133,0.130644,439,0.001394,314848,241673.0,219390.0,73175.0,...,102.0,5.0,3.074499,0.323966,-49.0,-36.0,52.0,-54.0,-45.0,10.0
3,Albany,2022-01-01,41133,0.130644,439,0.001394,314848,241673.0,219390.0,73175.0,...,102.0,5.0,3.074499,0.323966,-49.0,-36.0,52.0,-54.0,-45.0,10.0
4,Albany,2021-01-10,14196,0.045088,231,0.000734,314848,12016.0,855.0,302832.0,...,163.0,30.0,3.957465,0.517710,-35.0,-13.0,34.0,-55.0,-19.0,8.0

In [40]:
check_missing_dates(df_final,dateCol='date')

DatetimeIndex(['2022-02-28', '2022-03-01'], dtype='datetime64[ns]', freq=None)

In [14]:
subset = df_final[df_final['date']>='01-04-2020']
len(subset), len(df_final)

(102108, 102108)

In [16]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102108 entries, 0 to 102107
Data columns (total 32 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   county                                         102108 non-null  object
 1   date                                           102108 non-null  datetime64[ns]
 2   daily_cases                                    102108 non-null  int64
 3   daily_cases_by_population                      102108 non-null  float64
 4   daily_deaths                                   102108 non-null  int64
 5   daily_deaths_by_population                     102108 non-null  float64
 6   Partially Vaccinated                           61576 non-null   float64
 7   Fully Vaccinated                               61576 non-null   float64
 8   POP2020                                        61576 non-null   float64
 9   Non Vaccinated                                 61576 non-null   float64
 10  Partially Vaccinated per Population            61576 non-null   float64
 11  Fully Vaccinated per Population                61576 non-null   float64
 12  Non Vaccinated per Population                  61576 non-null   float64
 13  Facility Name                                  93366 non-null   object
 14  Patients Age 55 to 64 Years                    93366 non-null   float64
 15  Patients Age 65 to 74 Years                    93366 non-null   float64
 16  Patients Age 75 to 84 Years                    93366 non-null   float64
 17  Patients Currently Hospitalized                93366 non-null   float64
 18  Patients Newly Admitted                        93366 non-null   float64
 19  Patients Positive After Admission              93366 non-null   float64
 20  Patients Currently in ICU                      93366 non-null   float64
 21  Patients Currently ICU Intubated               93366 non-null   float64
 22  Total Beds                                     93366 non-null   float64
 23  Number of Beds Available                       93366 non-null   float64
 24  Number of ICU Beds                             93366 non-null   float64
 25  Number of ICU Beds Available                   93366 non-null   float64
 26  Total Beds By County                           93366 non-null   float64
 27  Number of Beds Available By County             93366 non-null   float64
 28  Number of ICU Beds By County                   93366 non-null   float64
 29  Number of ICU Beds Available By County         93366 non-null   float64
 30  Total Beds By County per thousand ppl          93366 non-null   float64
 31  Number of ICU Beds By County per thousand ppl  93366 non-null   float64
dtypes: datetime64[ns](1), float64(27), int64(2), object(2)
memory usage: 25.7+ MB

In [27]:
df_merged = pd.read_parquet('../data/final_dataset.parquet.gzip')
print(df_merged.isna().sum())

county                                                   0
date                                                     0
daily_cases                                              0
daily_cases_by_population                                0
daily_deaths                                             0
daily_deaths_by_population                               0
POP2020                                                  0
Partially Vaccinated                                     0
Fully Vaccinated                                         0
Non Vaccinated                                           0
Partially Vaccinated per Population                      0
Fully Vaccinated per Population                          0
Non Vaccinated per Population                            0
Facility Name                                         5030
Patients Age 55 to 64 Years                           5030
Patients Age 65 to 74 Years                           5030
Patients Age 75 to 84 Years                           5030
Patients Currently Hospitalized                       5030
Patients Newly Admitted                               5030
Patients Positive After Admission                     5030
Patients Currently in ICU                             5030
Patients Currently ICU Intubated                      5030
Total Beds                                            5030
Number of Beds Available                              5030
Number of ICU Beds                                    5030
Number of ICU Beds Available                          5030
Total Beds By County                                  5030
Number of Beds Available By County                    5030
Number of ICU Beds By County                          5030
Number of ICU Beds Available By County                5030
Total Beds By County per thousand ppl                 5030
Number of ICU Beds By County per thousand ppl         5030
retail_and_recreation_percent_change_from_baseline    1188
grocery_and_pharmacy_percent_change_from_baseline     1188
parks_percent_change_from_baseline                    1188
transit_stations_percent_change_from_baseline         1188
workplaces_percent_change_from_baseline               1188
residential_percent_change_from_baseline              1188
dtype: int64

In [31]:
df_merged[df_merged['Facility Name'].isna()].head()

,county,date,daily_cases,daily_cases_by_population,daily_deaths,daily_deaths_by_population,POP2020,Partially Vaccinated,Fully Vaccinated,Non Vaccinated,...,Number of ICU Beds By County,Number of ICU Beds Available By County,Total Beds By County per thousand ppl,Number of ICU Beds By County per thousand ppl,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
318,Albany,2021-11-25,33929,0.107763,409,0.001299,314848,228582.0,205205.0,86266.0,...,NaN,NaN,NaN,NaN,-78.0,-47.0,-33.0,-60.0,-87.0,19.0
437,Albany,2021-12-25,38669,0.122818,437,0.001388,314848,240291.0,218387.0,74557.0,...,NaN,NaN,NaN,NaN,-89.0,-79.0,-12.0,-61.0,-68.0,9.0
1724,Allegany,2021-11-25,5867,0.126311,119,0.002562,46449,20787.0,19155.0,25662.0,...,NaN,NaN,NaN,NaN,-64.0,-34.0,-4.0,-51.0,-85.0,14.0
1843,Allegany,2021-12-25,6839,0.147237,134,0.002885,46449,22245.0,20624.0,24204.0,...,NaN,NaN,NaN,NaN,-83.0,-79.0,-4.0,-51.0,-64.0,13.0
3289,Broome,2021-11-25,27865,0.140249,432,0.002174,198683,123766.0,114275.0,74917.0,...,NaN,NaN,NaN,NaN,-77.0,-40.0,50.0,-53.0,-85.0,17.0

In [34]:
subset = df_merged.copy()
subset = subset.set_index(['date','county'])
subset = subset.sort_values(by=['date'], ascending=True)
subset.head()

                   daily_cases  daily_cases_by_population  daily_deaths  \
date       county
2020-03-26 Cayuga            2                   0.000026             0
           Oneida           13                   0.000056             0
           Oneida           13                   0.000056             0
           Erie            206                   0.000216             2
           Oneida           13                   0.000056             0

                   daily_deaths_by_population  POP2020  Partially Vaccinated  \
date       county
2020-03-26 Cayuga                    0.000000    76248                   0.0
           Oneida                    0.000000   232125                   0.0
           Oneida                    0.000000   232125                   0.0
           Erie                      0.000002   952081                   0.0
           Oneida                    0.000000   232125                   0.0

                   Fully Vaccinated  Non Vaccinated  \
date       county
2020-03-26 Cayuga               0.0             0.0
           Oneida               0.0             0.0
           Oneida               0.0             0.0
           Erie                 0.0             0.0
           Oneida               0.0             0.0

                   Partially Vaccinated per Population  \
date       county
2020-03-26 Cayuga                                  0.0
           Oneida                                  0.0
           Oneida                                  0.0
           Erie                                    0.0
           Oneida                                  0.0

                   Fully Vaccinated per Population  ...  \
date       county                                   ...
2020-03-26 Cayuga                              0.0  ...
           Oneida                              0.0  ...
           Oneida                              0.0  ...
           Erie                                0.0  ...
           Oneida                              0.0  ...

                   Number of ICU Beds By County  \
date       county
2020-03-26 Cayuga                          10.0
           Oneida                          50.0
           Oneida                          50.0
           Erie                           234.0
           Oneida                          50.0

                  Number of ICU Beds Available By County  \
date       county
2020-03-26 Cayuga                                    8.0
           Oneida                                   14.0
           Oneida                                   14.0
           Erie                                     76.0
           Oneida                                   14.0

                   Total Beds By County per thousand ppl  \
date       county
2020-03-26 Cayuga                               1.127898
           Oneida                               2.132472
           Oneida                               2.132472
           Erie                                 2.382150
           Oneida                               2.132472

                   Number of ICU Beds By County per thousand ppl  \
date       county
2020-03-26 Cayuga                                       0.131151
           Oneida                                       0.215401
           Oneida                                       0.215401
           Erie                                         0.245777
           Oneida                                       0.215401

                   retail_and_recreation_percent_change_from_baseline  \
date       county
2020-03-26 Cayuga                                              -38.0
           Oneida                                              -36.0
           Oneida                                              -36.0
           Erie                                                -47.0
           Oneida                                              -36.0

                   grocery_and_pharmacy_percent_change_from_baseline  \
date       county
2020-03-26 Cayuga                                              -13.0
           Oneida                                              -15.0
           Oneida                                              -15.0
           Erie                                                -16.0
           Oneida                                              -15.0

                   parks_percent_change_from_baseline  \
date       county
2020-03-26 Cayuga                               -11.0
           Oneida                                83.0
           Oneida                                83.0
           Erie                                  50.0
           Oneida                                83.0

                   transit_stations_percent_change_from_baseline  \
date       county
2020-03-26 Cayuga                                          -34.0
           Oneida                                          -34.0
           Oneida                                          -34.0
           Erie                                            -47.0
           Oneida                                          -34.0

                   workplaces_percent_change_from_baseline  \
date       county
2020-03-26 Cayuga                                    -43.0
           Oneida                                    -45.0
           Oneida                                    -45.0
           Erie                                      -54.0
           Oneida                                    -45.0

                   residential_percent_change_from_baseline
date       county
2020-03-26 Cayuga                                      17.0
           Oneida                                      17.0
           Oneida                                      17.0
           Erie                                        21.0
           Oneida                                      17.0

[5 rows x 36 columns]

In [47]:
# counties = df_merged.county.unique()
# check_missing_dates(subset.reset_index(),'date')
df_final.groupby(by=['county'])['date'].nunique().unique()

array([704])