In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('../data/NY/vaccination.parquet.gzip')
df.head()

,Region,County,Partially Vaccinated,Fully Vaccinated,Report as of,POP2020,Non Vaccinated,Partially Vaccinated per Population,Fully Vaccinated per Population,Non Vaccinated per Population
0,Capital Region,Albany,74,0,2020-12-14,314848,314774,2.350340e-04,0.0,0.999765
1,Western New York,Allegany,0,0,2020-12-14,46449,46449,0.000000e+00,0.0,1.000000
2,New York City,"New York, Bronx, Kings, Richmond, Queens",2,0,2020-12-14,8804190,8804188,2.271646e-07,0.0,1.000000
3,Southern Tier,Broome,0,0,2020-12-14,198683,198683,0.000000e+00,0.0,1.000000
4,Western New York,Cattaraugus,0,0,2020-12-14,75467,75467,0.000000e+00,0.0,1.000000

In [7]:
df = df.sort_values(by=['Report as of'])
df.head()

,Region,County,Partially Vaccinated,Fully Vaccinated,Report as of,POP2020,Non Vaccinated,Partially Vaccinated per Population,Fully Vaccinated per Population,Non Vaccinated per Population
0,Capital Region,Albany,74,0,2020-12-14,314848,314774,2.350340e-04,0.0,0.999765
30,New York City,"New York, Bronx, Kings, Richmond, Queens",24,0,2020-12-14,8804190,8804166,2.725975e-06,0.0,0.999997
2,New York City,"New York, Bronx, Kings, Richmond, Queens",2,0,2020-12-14,8804190,8804188,2.271646e-07,0.0,1.000000
3,Southern Tier,Broome,0,0,2020-12-14,198683,198683,0.000000e+00,0.0,1.000000
4,Western New York,Cattaraugus,0,0,2020-12-14,75467,75467,0.000000e+00,0.0,1.000000

In [12]:
#check missing dates
subset = df.copy()
subset = subset.set_index('Report as of')
subset.index = pd.to_datetime(subset.index)
print(pd.date_range(
  start="2020-12-14", end="2022-05-01").difference(subset.index))

DatetimeIndex(['2022-03-06', '2022-03-07', '2022-03-08', '2022-03-09',
               '2022-03-10', '2022-03-11', '2022-03-12', '2022-03-13',
               '2022-03-14', '2022-03-15', '2022-03-16', '2022-03-17',
               '2022-03-18', '2022-03-19', '2022-03-20', '2022-03-21',
               '2022-03-22', '2022-03-23', '2022-03-24', '2022-03-25',
               '2022-03-26', '2022-03-27', '2022-03-28', '2022-03-29',
               '2022-03-30', '2022-03-31', '2022-04-01', '2022-04-02',
               '2022-04-03', '2022-04-04', '2022-04-05', '2022-04-06',
               '2022-04-07', '2022-04-08', '2022-04-09', '2022-04-10',
               '2022-04-11', '2022-04-12', '2022-04-13', '2022-04-14',
               '2022-04-15', '2022-04-16', '2022-04-17', '2022-04-18',
               '2022-04-19', '2022-04-20', '2022-04-21', '2022-04-22',
               '2022-04-23', '2022-04-24', '2022-04-25', '2022-04-26',
               '2022-04-27', '2022-04-28', '2022-04-29', '2022-04-30',
               '2022-05-01'],
              dtype='datetime64[ns]', freq=None)