# **Data Integration**

*   Vaccination
*   Cases
*   Deaths
*   Hospitalization
*   Mobility

In [1]:
# !pip install -U dataprep

In [1]:
import pandas as pd
# from dataprep.eda import plot

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')
# path = '/content/drive/MyDrive/CMPT_733_Project/'
path = '../data/google_mobility_data/'

## **Clean Mobility Data**

In [3]:
mobility_2020 = pd.read_csv(path+'2020_US_Region_Mobility_Report.csv', parse_dates=['date'])
mobility_2021 = pd.read_csv(path+'2021_US_Region_Mobility_Report.csv', parse_dates=['date'])
mobility_2022 = pd.read_csv(path+'2022_US_Region_Mobility_Report.csv', parse_dates=['date'])

In [4]:
mobility_2020 = mobility_2020[mobility_2020['sub_region_1']=='New York']
mobility_2021 = mobility_2021[mobility_2021['sub_region_1']=='New York']
mobility_2022 = mobility_2022[mobility_2022['sub_region_1']=='New York']

In [5]:
mobility_2020['sub_region_2'] = mobility_2020['sub_region_2'].str.replace(' County','')
mobility_2021['sub_region_2'] = mobility_2021['sub_region_2'].str.replace(' County','')
mobility_2022['sub_region_2'] = mobility_2022['sub_region_2'].str.replace(' County','')

In [6]:
mobility_2020 = mobility_2020.dropna(axis=0, subset=['sub_region_2'])
mobility_2021 = mobility_2021.dropna(axis=0, subset=['sub_region_2'])
mobility_2022 = mobility_2022.dropna(axis=0, subset=['sub_region_2'])

In [7]:
mobility_2020.loc[mobility_2020['sub_region_2'].isin(['New York', 'Bronx', 'Kings', 'Queens', 'Richmond']), 'sub_region_2'] = 'New York, Bronx, Kings, Richmond, Queens'
mobility_2021.loc[mobility_2021['sub_region_2'].isin(['New York', 'Bronx', 'Kings', 'Queens', 'Richmond']), 'sub_region_2'] = 'New York, Bronx, Kings, Richmond, Queens'
mobility_2022.loc[mobility_2022['sub_region_2'].isin(['New York', 'Bronx', 'Kings', 'Queens', 'Richmond']), 'sub_region_2'] = 'New York, Bronx, Kings, Richmond, Queens'

mobility_2020.loc[mobility_2020['sub_region_2'].isin(['St. Lawrence']), 'sub_region_2'] = 'St Lawrence'
mobility_2021.loc[mobility_2021['sub_region_2'].isin(['St. Lawrence']), 'sub_region_2'] = 'St Lawrence'
mobility_2022.loc[mobility_2022['sub_region_2'].isin(['St. Lawrence']), 'sub_region_2'] = 'St Lawrence'

In [8]:
mobility_2020 = mobility_2020.drop(['metro_area', 'iso_3166_2_code', 'census_fips_code', 'place_id'], axis=1)
mobility_2021 = mobility_2021.drop(['metro_area', 'iso_3166_2_code', 'census_fips_code', 'place_id'], axis=1)
mobility_2022 = mobility_2022.drop(['metro_area', 'iso_3166_2_code', 'census_fips_code', 'place_id'], axis=1)

In [9]:
len(mobility_2020.sub_region_2.unique())

57

In [10]:
counties_to_exclude = ['Washington', 'Hamilton', 'Greene', 'Tioga', 'Seneca', 'Ontario, Seneca']
mobility_2020 = mobility_2020[~mobility_2020['sub_region_2'].isin(counties_to_exclude)]
mobility_2021 = mobility_2021[~mobility_2021['sub_region_2'].isin(counties_to_exclude)]
mobility_2022 = mobility_2022[~mobility_2022['sub_region_2'].isin(counties_to_exclude)]

In [12]:
# hsp_counties = hospitalization['Facility County'].unique()
# counties_58 = cases['county'].unique()
# mob = mobility_2020.sub_region_2.unique()
# [_ for _ in counties_58 if str.upper(_) not in hsp_counties],[_ for _ in counties_58 if _ not in mob]

In [11]:
mobility_2020 = mobility_2020.groupby(['country_region_code', 'country_region', 'sub_region_1', 'sub_region_2', 'date'])['retail_and_recreation_percent_change_from_baseline', 'grocery_and_pharmacy_percent_change_from_baseline', 'parks_percent_change_from_baseline', 'transit_stations_percent_change_from_baseline', 'workplaces_percent_change_from_baseline', 'residential_percent_change_from_baseline'].mean()
mobility_2021 = mobility_2021.groupby(['country_region_code', 'country_region', 'sub_region_1', 'sub_region_2', 'date'])['retail_and_recreation_percent_change_from_baseline', 'grocery_and_pharmacy_percent_change_from_baseline', 'parks_percent_change_from_baseline', 'transit_stations_percent_change_from_baseline', 'workplaces_percent_change_from_baseline', 'residential_percent_change_from_baseline'].mean()
mobility_2022 = mobility_2022.groupby(['country_region_code', 'country_region', 'sub_region_1', 'sub_region_2', 'date'])['retail_and_recreation_percent_change_from_baseline', 'grocery_and_pharmacy_percent_change_from_baseline', 'parks_percent_change_from_baseline', 'transit_stations_percent_change_from_baseline', 'workplaces_percent_change_from_baseline', 'residential_percent_change_from_baseline'].mean()

/var/folders/0n/tmqs18m12qv19g7f3mp1sy6c0000gn/T/ipykernel_33738/1049665467.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  mobility_2020 = mobility_2020.groupby(['country_region_code', 'country_region', 'sub_region_1', 'sub_region_2', 'date'])['retail_and_recreation_percent_change_from_baseline', 'grocery_and_pharmacy_percent_change_from_baseline', 'parks_percent_change_from_baseline', 'transit_stations_percent_change_from_baseline', 'workplaces_percent_change_from_baseline', 'residential_percent_change_from_baseline'].mean()
/var/folders/0n/tmqs18m12qv19g7f3mp1sy6c0000gn/T/ipykernel_33738/1049665467.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  mobility_2021 = mobility_2021.groupby(['country_region_code', 'country_region', 'sub_region_1', 'sub_region_2', 'date'])['retail_and_recreation_percent_change_from_baseline', 'grocery_and_pharmacy_percent_change_from_baseline', 'parks_percent_change_from_baseline', 'transit_stations_percent_change_from_baseline', 'workplaces_percent_change_from_baseline', 'residential_percent_change_from_baseline'].mean()
/var/folders/0n/tmqs18m12qv19g7f3mp1sy6c0000gn/T/ipykernel_33738/1049665467.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  mobility_2022 = mobility_2022.groupby(['country_region_code', 'country_region', 'sub_region_1', 'sub_region_2', 'date'])['retail_and_recreation_percent_change_from_baseline', 'grocery_and_pharmacy_percent_change_from_baseline', 'parks_percent_change_from_baseline', 'transit_stations_percent_change_from_baseline', 'workplaces_percent_change_from_baseline', 'residential_percent_change_from_baseline'].mean()

In [12]:
mobility_2020 = mobility_2020.reset_index()
mobility_2021 = mobility_2021.reset_index()
mobility_2022 = mobility_2022.reset_index()

In [13]:
mobility_2020 = mobility_2020.set_index(['date', 'sub_region_2'])
mobility_2021 = mobility_2021.set_index(['date', 'sub_region_2'])
mobility_2022 = mobility_2022.set_index(['date', 'sub_region_2'])

In [14]:
mobility_2020 = mobility_2020.fillna(method='ffill')
mobility_2021 = mobility_2021.fillna(method='ffill')
mobility_2022 = mobility_2022.fillna(method='ffill')

In [15]:
mobility_2020 = mobility_2020.reset_index()
mobility_2021 = mobility_2021.reset_index()
mobility_2022 = mobility_2022.reset_index()

In [16]:
mobility = mobility_2020.append(mobility_2021, ignore_index=True)
mobility = mobility.append(mobility_2022, ignore_index=True)

In [17]:
mobility.to_parquet('mobility.parquet.gzip', compression='gzip')

**Merge Data**

In [18]:
path = '../data/NY/'

In [20]:
vaccine = pd.read_parquet(path+'vaccination.parquet.gzip')
cases = pd.read_parquet(path+'countywise_daily_cases.parquet.gzip')
deaths = pd.read_parquet(path+'countywise_daily_deaths.parquet.gzip')
hospitalization = pd.read_parquet('../data/NY_hospitals_beds_final_df.parquet')

In [21]:
counties_to_keep  = hospitalization['Facility County'].unique()
counties_to_keep = list(map(str.capitalize,map(str.lower,counties_to_keep)))
vaccine = vaccine.rename(columns={"Report as of": "date"})
vaccine = vaccine[vaccine['County'].str.capitalize().isin(counties_to_keep)]
vaccine.head()

,Region,County,date,Partially Vaccinated,Fully Vaccinated,POP2020,Non Vaccinated,Partially Vaccinated per Population,Fully Vaccinated per Population,Non Vaccinated per Population
0,Capital Region,Albany,2020-12-14,74,0,314848,314774,0.000235,0.000000,0.999765
1,Capital Region,Albany,2020-12-15,187,0,314848,314661,0.000594,0.000000,0.999406
2,Capital Region,Albany,2020-12-16,377,3,314848,314471,0.001197,0.000010,0.998803
3,Capital Region,Albany,2020-12-17,460,3,314848,314388,0.001461,0.000010,0.998539
4,Capital Region,Albany,2020-12-18,704,4,314848,314144,0.002236,0.000013,0.997764

In [22]:
cases = cases[cases['county'].str.capitalize().isin(counties_to_keep)]
cases.head()

   county       date  daily_cases
0  Albany 2020-01-22          0.0
1  Albany 2020-01-23          0.0
2  Albany 2020-01-24          0.0
3  Albany 2020-01-25          0.0
4  Albany 2020-01-26          0.0

In [23]:
deaths = deaths[deaths['county'].str.capitalize().isin(counties_to_keep)]
deaths.head()

   county       date  daily_deaths
0  Albany 2020-01-22           0.0
1  Albany 2020-01-23           0.0
2  Albany 2020-01-24           0.0
3  Albany 2020-01-25           0.0
4  Albany 2020-01-26           0.0

In [24]:
print(len(vaccine['County'].unique()), len(cases['county'].unique()), len(deaths['county'].unique()))
vac_counties = vaccine['County'].unique()
[_ for _ in vac_counties if str.capitalize(_) not in counties_to_keep]

53 53 53

[]

In [25]:
counties_to_keep

['Otsego',
 'Franklin',
 'Albany',
 'Chemung',
 'Cayuga',
 'New york, bronx, kings, richmond, queens',
 'Erie',
 'Westchester',
 'Orange',
 'Chautauqua',
 'St lawrence',
 'Jefferson',
 'Sullivan',
 'Tompkins',
 'Chenango',
 'Ontario',
 'Schoharie',
 'Columbia',
 'Madison',
 'Steuben',
 'Onondaga',
 'Allegany',
 'Niagara',
 'Delaware',
 'Ulster',
 'Schenectady',
 'Oneida',
 'Nassau',
 'Warren',
 'Suffolk',
 'Rockland',
 'Cortland',
 'Monroe',
 'Lewis',
 'Herkimer',
 'Orleans',
 'Dutchess',
 'Fulton',
 'Wayne',
 'Livingston',
 'Cattaraugus',
 'Oswego',
 'Broome',
 'Putnam',
 'Rensselaer',
 'Saratoga',
 'Schuyler',
 'Yates',
 'Montgomery',
 'Essex',
 'Clinton',
 'Genesee',
 'Wyoming']

In [26]:
hospitalization = hospitalization.reset_index()
hospitalization['Facility County'] = hospitalization['Facility County'].str.title()
hospitalization = hospitalization.rename(columns={'As of Date':'date', 'Facility County':'county'})
hospitalization = hospitalization.drop(['POP2020'], axis=1)
hospitalization = hospitalization.drop_duplicates()
hospitalization.tail()

,date,Facility Name,county,Patients Age 55 to 64 Years,Patients Age 65 to 74 Years,Patients Age 75 to 84 Years,Patients Currently Hospitalized,Patients Newly Admitted,Patients Positive After Admission,Patients Currently in ICU,...,Total Beds,Number of Beds Available,Number of ICU Beds,Number of ICU Beds Available,Total Beds By County,Number of Beds Available By County,Number of ICU Beds By County,Number of ICU Beds Available By County,Total Beds By County per thousand ppl,Number of ICU Beds By County per thousand ppl
133755,2022-02-27,WHITE PLAINS HOSPITAL CENTER,Westchester,1.0,1.0,1.0,5.0,2.0,0.0,0.0,...,220.0,30.0,16.0,8.0,1849.0,535.0,237.0,56.0,1.840796,0.235948
133756,2022-02-27,WINIFRED MASTERSON BURKE REHABILITATION HOSPITAL,Westchester,1.0,2.0,3.0,7.0,0.0,0.0,0.0,...,150.0,26.0,0.0,0.0,1849.0,535.0,237.0,56.0,1.840796,0.235948
133757,2022-02-27,WOODHULL MEDICAL AND MENTAL HEALTH CENTER,"New York, Bronx, Kings, Richmond, Queens",1.0,1.0,0.0,7.0,0.0,0.0,0.0,...,144.0,46.0,12.0,8.0,15484.0,4274.0,2066.0,521.0,1.758708,0.234661
133758,2022-02-27,WYCKOFF HEIGHTS MEDICAL CENTER,"New York, Bronx, Kings, Richmond, Queens",0.0,1.0,1.0,4.0,0.0,1.0,0.0,...,162.0,22.0,24.0,7.0,15484.0,4274.0,2066.0,521.0,1.758708,0.234661
133759,2022-02-27,WYOMING COUNTY COMMUNITY HOSPITAL,Wyoming,0.0,1.0,1.0,2.0,1.0,0.0,0.0,...,25.0,3.0,6.0,5.0,25.0,3.0,6.0,5.0,0.616812,0.148035

In [27]:
vaccine = vaccine[(vaccine['date']<'2022-02-28') & (vaccine['date']>'2020-03-25')]
cases = cases[(cases['date']<'2022-02-28') & (cases['date']>'2020-03-25')]
deaths = deaths[(deaths['date']<'2022-02-28') & (deaths['date']>'2020-03-25')]
hospitalization = hospitalization[(hospitalization['date']<'2022-02-28') & (hospitalization['date']>'2020-03-25')]
mobility = mobility[(mobility['date']<'2022-02-28') & (mobility['date']>'2020-03-25')]

In [28]:
print(cases['date'].min())
print(deaths['date'].min())
print(hospitalization['date'].min())
print(mobility['date'].min())

2020-03-26 00:00:00
2020-03-26 00:00:00
2020-03-26 00:00:00
2020-03-26 00:00:00

In [29]:
final_df = pd.merge(cases, deaths, how='left', left_on=['county', 'date'], right_on=['county', 'date'])
temp_vaccine = vaccine[['County', 'POP2020']]
temp_vaccine = temp_vaccine.drop_duplicates()
final_df = pd.merge(final_df, temp_vaccine, how='left', left_on=['county'], right_on=['County'])

final_df = final_df.drop(['County'], axis=1)
vaccine_2 = vaccine.drop(['POP2020'], axis=1)
final_df = pd.merge(final_df, vaccine_2, how='left', left_on=['county', 'date'], right_on=['County', 'date'])
final_df = final_df.drop(['Region', 'County'], axis=1)
final_df.isna().sum(), len(final_df)
# final_df = pd.merge(final_df, hospitalization, how='left', left_on=['county', 'date'], right_on=['county', 'date'])

(county                                     0
 date                                       0
 daily_cases                                0
 daily_deaths                               0
 POP2020                                    0
 Partially Vaccinated                   13939
 Fully Vaccinated                       13939
 Non Vaccinated                         13939
 Partially Vaccinated per Population    13939
 Fully Vaccinated per Population        13939
 Non Vaccinated per Population          13939
 dtype: int64,
 37312)

In [30]:
final_df['Partially Vaccinated'] = final_df['Partially Vaccinated'].fillna(0)
final_df['Fully Vaccinated'] = final_df['Fully Vaccinated'].fillna(0)
final_df['Non Vaccinated'] = final_df['Non Vaccinated'].fillna(0)

In [31]:
final_df['Partially Vaccinated'] = final_df['Partially Vaccinated'].fillna(0)
final_df['Fully Vaccinated'] = final_df['Fully Vaccinated'].fillna(0)
final_df['Non Vaccinated'] = final_df['Non Vaccinated'].fillna(0)
final_df['Partially Vaccinated per Population'] = final_df['Partially Vaccinated per Population'].fillna(0)
final_df['Fully Vaccinated per Population'] = final_df['Fully Vaccinated per Population'].fillna(0)
final_df['Non Vaccinated per Population'] = final_df['Non Vaccinated per Population'].fillna(0)

In [32]:
# check missing dates
def check_missing_dates(df, dateCol):
    subset = df.copy()
    subset = subset.set_index(dateCol)
    subset.index = pd.to_datetime(subset.index)
    print(pd.date_range(
        start="2020-03-26", end="2022-03-01").difference(subset.index))

In [33]:
check_missing_dates(final_df,'date'), check_missing_dates(hospitalization,'date')

DatetimeIndex(['2022-02-28', '2022-03-01'], dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2022-02-28', '2022-03-01'], dtype='datetime64[ns]', freq=None)

(None, None)

In [34]:
d2 = pd.read_parquet('../data/NY_hospitals_beds_final_df.parquet')
check_missing_dates(d2.reset_index(),'As of Date')

DatetimeIndex(['2022-02-28', '2022-03-01'], dtype='datetime64[ns]', freq=None)

In [36]:
# f_dates = final_df.groupby(by=['date','county']).count()
# f_list = f_dates.index.to_list()
# h_dates = hospitalization.groupby(by=['date','county']).count()
# h_list = h_dates.index.to_list()

# [_ for _ in f_list if _ not in h_list]

In [35]:
final_df = pd.merge(final_df, hospitalization, how='inner', left_on=['date','county'], right_on=[ 'date','county'])

# hospitalization.columns

In [36]:
# mobility = mobility.drop(['index'], axis=1)
mobility.head()

,date,sub_region_2,country_region_code,country_region,sub_region_1,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
40,2020-03-26,Albany,US,United States,New York,-51.0,-11.0,43.0,-53.0,-55.0,23.0
41,2020-03-27,Albany,US,United States,New York,-52.0,-15.0,41.0,-52.0,-55.0,24.0
42,2020-03-28,Albany,US,United States,New York,-59.0,-25.0,33.0,-59.0,-37.0,14.0
43,2020-03-29,Albany,US,United States,New York,-59.0,-30.0,-15.0,-64.0,-36.0,13.0
44,2020-03-30,Albany,US,United States,New York,-51.0,-19.0,-37.0,-60.0,-56.0,23.0

In [37]:
# f_dates = final_df.groupby(by=['date','county']).count()
# f_list = f_dates.index.to_list()
# h_dates = mobility.groupby(by=['date','sub_region_2']).count()
# h_list = h_dates.index.to_list()

# [_ for _ in f_list if _ not in h_list]

# f_counties = final_df.county.unique()
# h_counties = mobility.sub_region_2.unique()
# [_ for _ in h_counties if _ not in f_counties]
check_missing_dates(mobility,'date')

DatetimeIndex(['2022-02-28', '2022-03-01'], dtype='datetime64[ns]', freq=None)

In [38]:
final_df = pd.merge(final_df, mobility, left_on=['date', 'county'], right_on=['date', 'sub_region_2'], how='left')
final_df = final_df.drop(['sub_region_2', 'sub_region_1', 'country_region', 'country_region_code'], axis=1)

In [39]:
mobility.isna().sum()

date                                                  0
sub_region_2                                          0
country_region_code                                   0
country_region                                        0
sub_region_1                                          0
retail_and_recreation_percent_change_from_baseline    0
grocery_and_pharmacy_percent_change_from_baseline     0
parks_percent_change_from_baseline                    0
transit_stations_percent_change_from_baseline         0
workplaces_percent_change_from_baseline               0
residential_percent_change_from_baseline              0
dtype: int64

In [40]:
# final_df.to_parquet('final_dataset.parquet.gzip', compression='gzip'
len(final_df.county.unique())

53

In [43]:
# final_df.to_parquet('../data/final_dataset.parquet',compression='gzip')

In [47]:
# final_df.isna().sum()
# final_df[final_df['parks_percent_change_from_baseline'].isna()]

,county,date,daily_cases,daily_cases_by_population,daily_deaths,daily_deaths_by_population,POP2020,Partially Vaccinated,Fully Vaccinated,Non Vaccinated,...,Number of ICU Beds By County,Number of ICU Beds Available By County,Total Beds By County per thousand ppl,Number of ICU Beds By County per thousand ppl,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
2628,Allegany,2020-08-22,84,0.001808,1,0.000022,46449,0.0,0.0,0.0,...,6.0,2.0,1.485500,0.129174,NaN,NaN,NaN,NaN,NaN,NaN
2629,Allegany,2020-08-22,84,0.001808,1,0.000022,46449,0.0,0.0,0.0,...,6.0,2.0,1.485500,0.129174,NaN,NaN,NaN,NaN,NaN,NaN
2632,Allegany,2020-08-23,85,0.001830,1,0.000022,46449,0.0,0.0,0.0,...,6.0,1.0,1.485500,0.129174,NaN,NaN,NaN,NaN,NaN,NaN
2633,Allegany,2020-08-23,85,0.001830,1,0.000022,46449,0.0,0.0,0.0,...,6.0,1.0,1.485500,0.129174,NaN,NaN,NaN,NaN,NaN,NaN
2656,Allegany,2020-08-29,88,0.001895,1,0.000022,46449,0.0,0.0,0.0,...,6.0,4.0,1.485500,0.129174,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133750,Yates,2020-09-05,62,0.002503,7,0.000283,24774,0.0,0.0,0.0,...,0.0,0.0,0.726568,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
133752,Yates,2020-09-06,62,0.002503,7,0.000283,24774,0.0,0.0,0.0,...,0.0,0.0,0.726568,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
133754,Yates,2020-09-07,62,0.002503,7,0.000283,24774,0.0,0.0,0.0,...,0.0,0.0,0.726568,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
133756,Yates,2020-09-08,62,0.002503,7,0.000283,24774,0.0,0.0,0.0,...,0.0,0.0,0.726568,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
133758,Yates,2020-09-09,62,0.002503,7,0.000283,24774,0.0,0.0,0.0,...,0.0,0.0,0.726568,0.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
x = final_df.set_index(['county','date']).sort_values(by=['county','date']).ffill()

In [42]:
x.loc[('Allegany','2020-08-22')]

                     daily_cases  daily_deaths  POP2020  Partially Vaccinated  \
county   date
Allegany 2020-08-22          0.0           0.0    46449                   0.0
         2020-08-22          0.0           0.0    46449                   0.0

                     Fully Vaccinated  Non Vaccinated  \
county   date
Allegany 2020-08-22               0.0             0.0
         2020-08-22               0.0             0.0

                     Partially Vaccinated per Population  \
county   date
Allegany 2020-08-22                                  0.0
         2020-08-22                                  0.0

                     Fully Vaccinated per Population  \
county   date
Allegany 2020-08-22                              0.0
         2020-08-22                              0.0

                     Non Vaccinated per Population  \
county   date
Allegany 2020-08-22                            0.0
         2020-08-22                            0.0

                                                         Facility Name  ...  \
county   date                                                           ...
Allegany 2020-08-22                         CUBA MEMORIAL HOSPITAL INC  ...
         2020-08-22  MEMORIAL HOSP OF WM F AND GERTRUDE F JONES AKA...  ...

                     Number of ICU Beds By County  \
county   date
Allegany 2020-08-22                           6.0
         2020-08-22                           6.0

                     Number of ICU Beds Available By County  \
county   date
Allegany 2020-08-22                                     2.0
         2020-08-22                                     2.0

                     Total Beds By County per thousand ppl  \
county   date
Allegany 2020-08-22                                 1.4855
         2020-08-22                                 1.4855

                     Number of ICU Beds By County per thousand ppl  \
county   date
Allegany 2020-08-22                                       0.129174
         2020-08-22                                       0.129174

                     retail_and_recreation_percent_change_from_baseline  \
county   date
Allegany 2020-08-22                                               -5.0
         2020-08-22                                               -5.0

                     grocery_and_pharmacy_percent_change_from_baseline  \
county   date
Allegany 2020-08-22                                               12.0
         2020-08-22                                               12.0

                     parks_percent_change_from_baseline  \
county   date
Allegany 2020-08-22                                -6.0
         2020-08-22                                -6.0

                     transit_stations_percent_change_from_baseline  \
county   date
Allegany 2020-08-22                                          -50.0
         2020-08-22                                          -50.0

                     workplaces_percent_change_from_baseline  \
county   date
Allegany 2020-08-22                                     -8.0
         2020-08-22                                     -8.0

                     residential_percent_change_from_baseline
county   date
Allegany 2020-08-22                                       4.0
         2020-08-22                                       4.0

[2 rows x 34 columns]

In [43]:
x.loc[('Allegany','2020-08-21')]

                     daily_cases  daily_deaths  POP2020  Partially Vaccinated  \
county   date
Allegany 2020-08-21          3.0           0.0    46449                   0.0
         2020-08-21          3.0           0.0    46449                   0.0

                     Fully Vaccinated  Non Vaccinated  \
county   date
Allegany 2020-08-21               0.0             0.0
         2020-08-21               0.0             0.0

                     Partially Vaccinated per Population  \
county   date
Allegany 2020-08-21                                  0.0
         2020-08-21                                  0.0

                     Fully Vaccinated per Population  \
county   date
Allegany 2020-08-21                              0.0
         2020-08-21                              0.0

                     Non Vaccinated per Population  \
county   date
Allegany 2020-08-21                            0.0
         2020-08-21                            0.0

                                                         Facility Name  ...  \
county   date                                                           ...
Allegany 2020-08-21                         CUBA MEMORIAL HOSPITAL INC  ...
         2020-08-21  MEMORIAL HOSP OF WM F AND GERTRUDE F JONES AKA...  ...

                     Number of ICU Beds By County  \
county   date
Allegany 2020-08-21                           6.0
         2020-08-21                           6.0

                     Number of ICU Beds Available By County  \
county   date
Allegany 2020-08-21                                     3.0
         2020-08-21                                     3.0

                     Total Beds By County per thousand ppl  \
county   date
Allegany 2020-08-21                                 1.4855
         2020-08-21                                 1.4855

                     Number of ICU Beds By County per thousand ppl  \
county   date
Allegany 2020-08-21                                       0.129174
         2020-08-21                                       0.129174

                     retail_and_recreation_percent_change_from_baseline  \
county   date
Allegany 2020-08-21                                               -5.0
         2020-08-21                                               -5.0

                     grocery_and_pharmacy_percent_change_from_baseline  \
county   date
Allegany 2020-08-21                                               12.0
         2020-08-21                                               12.0

                     parks_percent_change_from_baseline  \
county   date
Allegany 2020-08-21                                -6.0
         2020-08-21                                -6.0

                     transit_stations_percent_change_from_baseline  \
county   date
Allegany 2020-08-21                                          -50.0
         2020-08-21                                          -50.0

                     workplaces_percent_change_from_baseline  \
county   date
Allegany 2020-08-21                                     -8.0
         2020-08-21                                     -8.0

                     residential_percent_change_from_baseline
county   date
Allegany 2020-08-21                                       4.0
         2020-08-21                                       4.0

[2 rows x 34 columns]

In [44]:
x.isna().sum()

daily_cases                                           0
daily_deaths                                          0
POP2020                                               0
Partially Vaccinated                                  0
Fully Vaccinated                                      0
Non Vaccinated                                        0
Partially Vaccinated per Population                   0
Fully Vaccinated per Population                       0
Non Vaccinated per Population                         0
Facility Name                                         0
Patients Age 55 to 64 Years                           0
Patients Age 65 to 74 Years                           0
Patients Age 75 to 84 Years                           0
Patients Currently Hospitalized                       0
Patients Newly Admitted                               0
Patients Positive After Admission                     0
Patients Currently in ICU                             0
Patients Currently ICU Intubated                      0
Total Beds                                            0
Number of Beds Available                              0
Number of ICU Beds                                    0
Number of ICU Beds Available                          0
Total Beds By County                                  0
Number of Beds Available By County                    0
Number of ICU Beds By County                          0
Number of ICU Beds Available By County                0
Total Beds By County per thousand ppl                 0
Number of ICU Beds By County per thousand ppl         0
retail_and_recreation_percent_change_from_baseline    0
grocery_and_pharmacy_percent_change_from_baseline     0
parks_percent_change_from_baseline                    0
transit_stations_percent_change_from_baseline         0
workplaces_percent_change_from_baseline               0
residential_percent_change_from_baseline              0
dtype: int64

In [45]:
x = x.reset_index().sort_values(by=['date']).reset_index()

In [47]:

x.to_parquet('../data/final_dataset_v3.parquet',compression='gzip')